"""tags lead

Revision ID: 216679667bbc
Revises: 798b99282d0f
Create Date: 2026-05-12 16:17:21.863088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '216679667bbc'
down_revision = '798b99282d0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
